// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"encoding/json"
	"github.com/gogf/gf/v2/errors/gerror"
	"go-service/internal/dao/jh_site/dao/internal"
	"go-service/internal/dao/jh_site/model/entity"
	"go-service/internal/dao/jinhuang/dao"
	"go-service/utility/helpers"
)

// adminDao is the data access object for the table admin.
// You can define custom methods on it to extend its functionality as needed.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is a globally accessible object for table admin operations.
	Admin = adminDao{internal.NewAdminDao()}
)

// Add your custom methods and functionality below.

const StatusOn = 1 //开启

//GetAdmin
/**
 * @desc：获取管理员
 * @param siteId
 * @return res
 * @return err
 * @author : Carson
 */
func GetAdmin(username string, password string) (admin *entity.Admin, err error) {

	Site, _ := dao.GetSiteObject()
	ctx := context.TODO()
	query := Admin.Ctx(ctx)

	where := map[string]interface{}{}
	where["site_id"] = Site.Id
	where["username"] = username
	//where["password"], _ = helpers.Bcrypt(password)
	where["status"] = StatusOn
	where["delete_at"] = 0

	res, err := query.Where(where).One()
	if err != nil {
		return nil, gerror.Wrap(err, "用户不存在")
	}
	jsonData, err := json.Marshal(res)
	if err != nil {
		return nil, gerror.Wrap(err, "json序列化失败")
	}
	err = json.Unmarshal(jsonData, &admin)
	if err != nil {
		return nil, gerror.Wrap(err, "json反序列化失败")
	}

	if ok := helpers.CompareBcrypt(admin.Password, password); ok != true {
		return nil, gerror.New("密码不正确")
	}

	return
}
