// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"go-service/internal/dao/jh_site/dao/internal"
	"go-service/internal/dao/jh_site/model/entity"
)

// adminRoleDao is the data access object for the table admin_role.
// You can define custom methods on it to extend its functionality as needed.
type adminRoleDao struct {
	*internal.AdminRoleDao
}

var (
	// AdminRole is a globally accessible object for table admin_role operations.
	AdminRole = adminRoleDao{internal.NewAdminRoleDao()}
)

// Add your custom methods and functionality below.

// 常量

var RoleStatusOn = 1 //开启

//GetRoleList
/**
 * @desc：获取站点职务列表
 * @param siteId
 * @return role
 * @return err
 * @author : Carson
 */
func GetRoleList(siteId uint) (role []*entity.AdminRole, err error) {

	//site.Id
	where := map[string]interface{}{}
	where["site_id"] = siteId
	where["status"] = RoleStatusOn

	err = AdminRole.Ctx(context.TODO()).Where(where).Fields("id", "name", "permissions").Scan(&role)
	if err != nil {
		return nil, err
	}

	return role, err
}
