// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/text/gstr"
	"github.com/gogf/gf/v2/util/gconv"
	"go-service/api/backendRoute"
	"go-service/internal/dao/jh_site/dao/internal"
	"go-service/internal/dao/jh_site/model/entity"
	daojh "go-service/internal/dao/jinhuang/dao"
	entityjh "go-service/internal/dao/jinhuang/model/entity"
)

// adminRoleDao is the data access object for the table admin_role.
// You can define custom methods on it to extend its functionality as needed.
type adminRoleDao struct {
	*internal.AdminRoleDao
}

var (
	// AdminRole is a globally accessible object for table admin_role operations.
	AdminRole = adminRoleDao{internal.NewAdminRoleDao()}
)

// Add your custom methods and functionality below.

// 常量

var RoleStatusOn = 1 //开启

//GetRoleList
/**
 * @desc：获取站点职务列表
 * @param siteId
 * @return role
 * @return err
 * @author : Carson
 */
func GetRoleList(siteId uint) (role []*entity.AdminRole, err error) {

	//site.Id
	where := map[string]interface{}{}
	where["site_id"] = siteId
	where["status"] = RoleStatusOn

	err = AdminRole.Ctx(context.TODO()).Where(where).Fields("id", "name", "permissions").Scan(&role)
	if err != nil {
		return nil, err
	}

	return role, err
}

//AddRole
/**
 * @desc：添加角色
 * @param ctx
 * @param siteId
 * @param req
 * @return error
 * @author : Carson
 */
func AddRole(ctx context.Context, siteId int, req *backendRoute.CreateReq) error {
	// 1. 先查是否存在
	var role *entity.AdminRole
	err := AdminRole.Ctx(ctx).
		Where("site_id", siteId).
		Where("name", req.Name).
		Scan(&role)

	if err != nil {
		return err
	}

	// 2. 已存在 → 返回提示
	if role != nil && role.Id > 0 {
		return gerror.New("角色名称已存在")
	}

	// 3. 不存在 → 插入
	_, err = AdminRole.Ctx(ctx).Insert(entity.AdminRole{
		Name:   req.Name,
		SiteId: siteId,
	})

	return err
}

//UpdateRole
/**
 * @desc：编辑角色
 * @param ctx
 * @param req
 * @return error
 * @author : Carson
 */
func UpdateRole(ctx context.Context, req *backendRoute.UpdateReq) error {
	// 转换 ID
	id := gconv.Int(req.Id)

	// 1. 查询是否存在
	var role *entity.AdminRole
	err := AdminRole.Ctx(ctx).Where("id", id).Scan(&role)
	if err != nil {
		return err
	}
	if role == nil {
		return gerror.New("角色不存在")
	}

	// 2. 更新（只更新需要的字段）
	_, err = AdminRole.Ctx(ctx).
		Where("id", id).
		Data(g.Map{
			"name": req.Name,
		}).
		Update()

	return err
}

func DeleteRole(ctx context.Context, req *backendRoute.DeleteReq) error {
	// 转换 ID
	id := gconv.Int(req.Id)

	// 1. 查询是否存在
	var role *entity.AdminRole
	err := AdminRole.Ctx(ctx).Where("id", id).Scan(&role)
	if err != nil {
		return err
	}
	if role == nil {
		return gerror.New("角色不存在")
	}

	// 2. 删除（只更新需要的字段）
	_, err = AdminRole.Ctx(ctx).Where("id", id).Delete()

	return err
}

//GetRole
/**
 * @desc：获取角色信息
 * @param ctx
 * @param roleId
 * @return role
 * @return err
 * @author : Carson
 */
func GetRole(ctx context.Context, roleId int) (role *entity.AdminRole, err error) {
	err = AdminRole.Ctx(ctx).Where("id", roleId).Scan(&role)
	return
}

//GetPermissionIds
/**
 * @desc：获取权限 ID 数组
 * @param role
 * @return []int
 * @author : Carson
 */
func GetPermissionIds(role *entity.AdminRole) []int {
	if role == nil || role.Permissions == "" {
		return []int{}
	}
	arr := gstr.Split(role.Permissions, ",")
	return gconv.Ints(arr)
}

//GetPermissions
/**
 * @desc：查询权限表信息
 * @param ctx
 * @param ids
 * @return []*entity.AdminPermission
 * @return error
 * @author : Carson
 */
func GetPermissions(ctx context.Context, ids []int) ([]*entityjh.AdminPermission, error) {
	var list []*entityjh.AdminPermission
	if len(ids) == 0 {
		return list, nil
	}

	err := daojh.AdminPermission.Ctx(ctx).
		WhereIn("id", ids).
		Where("status", 1).
		Order("sort asc").
		Scan(&list)

	return list, err
}
