// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_site/dao/internal"
)

// siteConfigDao is the data access object for the table site_config.
// You can define custom methods on it to extend its functionality as needed.
type siteConfigDao struct {
	*internal.SiteConfigDao
}

var (
	// SiteConfig is a globally accessible object for table site_config operations.
	SiteConfig = siteConfigDao{internal.NewSiteConfigDao()}
)

// Add your custom methods and functionality below.
