// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogExtraDao is the data access object for the table balance_log_extra.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogExtraDao struct {
	*internal.BalanceLogExtraDao
}

var (
	// BalanceLogExtra is a globally accessible object for table balance_log_extra operations.
	BalanceLogExtra = balanceLogExtraDao{internal.NewBalanceLogExtraDao()}
)

// Add your custom methods and functionality below.
