// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogBonusDao is the data access object for the table balance_log_bonus.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusDao struct {
	*internal.BalanceLogBonusDao
}

var (
	// BalanceLogBonus is a globally accessible object for table balance_log_bonus operations.
	BalanceLogBonus = balanceLogBonusDao{internal.NewBalanceLogBonusDao()}
)

// Add your custom methods and functionality below.
