// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceSiteDao is the data access object for the table balance_site.
// You can define custom methods on it to extend its functionality as needed.
type balanceSiteDao struct {
	*internal.BalanceSiteDao
}

var (
	// BalanceSite is a globally accessible object for table balance_site operations.
	BalanceSite = balanceSiteDao{internal.NewBalanceSiteDao()}
)

// Add your custom methods and functionality below.
