// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogBonusBirthdayDao is the data access object for the table balance_log_bonus_birthday.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusBirthdayDao struct {
	*internal.BalanceLogBonusBirthdayDao
}

var (
	// BalanceLogBonusBirthday is a globally accessible object for table balance_log_bonus_birthday operations.
	BalanceLogBonusBirthday = balanceLogBonusBirthdayDao{internal.NewBalanceLogBonusBirthdayDao()}
)

// Add your custom methods and functionality below.
