// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogBonusTransferDao is the data access object for the table balance_log_bonus_transfer.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusTransferDao struct {
	*internal.BalanceLogBonusTransferDao
}

var (
	// BalanceLogBonusTransfer is a globally accessible object for table balance_log_bonus_transfer operations.
	BalanceLogBonusTransfer = balanceLogBonusTransferDao{internal.NewBalanceLogBonusTransferDao()}
)

// Add your custom methods and functionality below.
