// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogRebateDao is the data access object for the table balance_log_rebate.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogRebateDao struct {
	*internal.BalanceLogRebateDao
}

var (
	// BalanceLogRebate is a globally accessible object for table balance_log_rebate operations.
	BalanceLogRebate = balanceLogRebateDao{internal.NewBalanceLogRebateDao()}
)

// Add your custom methods and functionality below.
