// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogBonusUpgradeDao is the data access object for the table balance_log_bonus_upgrade.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusUpgradeDao struct {
	*internal.BalanceLogBonusUpgradeDao
}

var (
	// BalanceLogBonusUpgrade is a globally accessible object for table balance_log_bonus_upgrade operations.
	BalanceLogBonusUpgrade = balanceLogBonusUpgradeDao{internal.NewBalanceLogBonusUpgradeDao()}
)

// Add your custom methods and functionality below.
