// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogBonusAgentDao is the data access object for the table balance_log_bonus_agent.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusAgentDao struct {
	*internal.BalanceLogBonusAgentDao
}

var (
	// BalanceLogBonusAgent is a globally accessible object for table balance_log_bonus_agent operations.
	BalanceLogBonusAgent = balanceLogBonusAgentDao{internal.NewBalanceLogBonusAgentDao()}
)

// Add your custom methods and functionality below.
