// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceRebateHistoryDao is the data access object for the table balance_rebate_history.
// You can define custom methods on it to extend its functionality as needed.
type balanceRebateHistoryDao struct {
	*internal.BalanceRebateHistoryDao
}

var (
	// BalanceRebateHistory is a globally accessible object for table balance_rebate_history operations.
	BalanceRebateHistory = balanceRebateHistoryDao{internal.NewBalanceRebateHistoryDao()}
)

// Add your custom methods and functionality below.
