// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogTransferDao is the data access object for the table balance_log_transfer.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogTransferDao struct {
	*internal.BalanceLogTransferDao
}

var (
	// BalanceLogTransfer is a globally accessible object for table balance_log_transfer operations.
	BalanceLogTransfer = balanceLogTransferDao{internal.NewBalanceLogTransferDao()}
)

// Add your custom methods and functionality below.
