// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogDao is the data access object for the table balance_log.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogDao struct {
	*internal.BalanceLogDao
}

var (
	// BalanceLog is a globally accessible object for table balance_log operations.
	BalanceLog = balanceLogDao{internal.NewBalanceLogDao()}
)

// Add your custom methods and functionality below.
