// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogWithdrawDao is the data access object for the table balance_log_withdraw.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogWithdrawDao struct {
	*internal.BalanceLogWithdrawDao
}

var (
	// BalanceLogWithdraw is a globally accessible object for table balance_log_withdraw operations.
	BalanceLogWithdraw = balanceLogWithdrawDao{internal.NewBalanceLogWithdrawDao()}
)

// Add your custom methods and functionality below.
