// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogRebateUserDao is the data access object for the table balance_log_rebate_user.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogRebateUserDao struct {
	*internal.BalanceLogRebateUserDao
}

var (
	// BalanceLogRebateUser is a globally accessible object for table balance_log_rebate_user operations.
	BalanceLogRebateUser = balanceLogRebateUserDao{internal.NewBalanceLogRebateUserDao()}
)

// Add your custom methods and functionality below.
