// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceRebateTimeDao is the data access object for the table balance_rebate_time.
// You can define custom methods on it to extend its functionality as needed.
type balanceRebateTimeDao struct {
	*internal.BalanceRebateTimeDao
}

var (
	// BalanceRebateTime is a globally accessible object for table balance_rebate_time operations.
	BalanceRebateTime = balanceRebateTimeDao{internal.NewBalanceRebateTimeDao()}
)

// Add your custom methods and functionality below.
