// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogExternalWalletOneDao is the data access object for the table balance_log_external_wallet_one.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogExternalWalletOneDao struct {
	*internal.BalanceLogExternalWalletOneDao
}

var (
	// BalanceLogExternalWalletOne is a globally accessible object for table balance_log_external_wallet_one operations.
	BalanceLogExternalWalletOne = balanceLogExternalWalletOneDao{internal.NewBalanceLogExternalWalletOneDao()}
)

// Add your custom methods and functionality below.
