// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// balanceLogManualDao is the data access object for the table balance_log_manual.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogManualDao struct {
	*internal.BalanceLogManualDao
}

var (
	// BalanceLogManual is a globally accessible object for table balance_log_manual operations.
	BalanceLogManual = balanceLogManualDao{internal.NewBalanceLogManualDao()}
)

// Add your custom methods and functionality below.
