// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_balance/dao/internal"
)

// pointsChangeDao is the data access object for the table points_change.
// You can define custom methods on it to extend its functionality as needed.
type pointsChangeDao struct {
	*internal.PointsChangeDao
}

var (
	// PointsChange is a globally accessible object for table points_change operations.
	PointsChange = pointsChangeDao{internal.NewPointsChangeDao()}
)

// Add your custom methods and functionality below.
