// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// activityWaterConfigDao is the data access object for the table activity_water_config.
// You can define custom methods on it to extend its functionality as needed.
type activityWaterConfigDao struct {
	*internal.ActivityWaterConfigDao
}

var (
	// ActivityWaterConfig is a globally accessible object for table activity_water_config operations.
	ActivityWaterConfig = activityWaterConfigDao{internal.NewActivityWaterConfigDao()}
)

// Add your custom methods and functionality below.
