// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// apiAgentConfigDao is the data access object for the table api_agent_config.
// You can define custom methods on it to extend its functionality as needed.
type apiAgentConfigDao struct {
	*internal.ApiAgentConfigDao
}

var (
	// ApiAgentConfig is a globally accessible object for table api_agent_config operations.
	ApiAgentConfig = apiAgentConfigDao{internal.NewApiAgentConfigDao()}
)

// Add your custom methods and functionality below.
