// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// betLogUserRebateDao is the data access object for the table bet_log_user_rebate.
// You can define custom methods on it to extend its functionality as needed.
type betLogUserRebateDao struct {
	*internal.BetLogUserRebateDao
}

var (
	// BetLogUserRebate is a globally accessible object for table bet_log_user_rebate operations.
	BetLogUserRebate = betLogUserRebateDao{internal.NewBetLogUserRebateDao()}
)

// Add your custom methods and functionality below.
