// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// channelDao is the data access object for the table channel.
// You can define custom methods on it to extend its functionality as needed.
type channelDao struct {
	*internal.ChannelDao
}

var (
	// Channel is a globally accessible object for table channel operations.
	Channel = channelDao{internal.NewChannelDao()}
)

// Add your custom methods and functionality below.
