// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// customResourceDao is the data access object for the table custom_resource.
// You can define custom methods on it to extend its functionality as needed.
type customResourceDao struct {
	*internal.CustomResourceDao
}

var (
	// CustomResource is a globally accessible object for table custom_resource operations.
	CustomResource = customResourceDao{internal.NewCustomResourceDao()}
)

// Add your custom methods and functionality below.
