// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// gameListDao is the data access object for the table game_list.
// You can define custom methods on it to extend its functionality as needed.
type gameListDao struct {
	*internal.GameListDao
}

var (
	// GameList is a globally accessible object for table game_list operations.
	GameList = gameListDao{internal.NewGameListDao()}
)

// Add your custom methods and functionality below.
