// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// gameConfigDao is the data access object for the table game_config.
// You can define custom methods on it to extend its functionality as needed.
type gameConfigDao struct {
	*internal.GameConfigDao
}

var (
	// GameConfig is a globally accessible object for table game_config operations.
	GameConfig = gameConfigDao{internal.NewGameConfigDao()}
)

// Add your custom methods and functionality below.
