// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// memberDayReportDao is the data access object for the table member_day_report.
// You can define custom methods on it to extend its functionality as needed.
type memberDayReportDao struct {
	*internal.MemberDayReportDao
}

var (
	// MemberDayReport is a globally accessible object for table member_day_report operations.
	MemberDayReport = memberDayReportDao{internal.NewMemberDayReportDao()}
)

// Add your custom methods and functionality below.
