// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// signInRecordsDao is the data access object for the table sign_in_records.
// You can define custom methods on it to extend its functionality as needed.
type signInRecordsDao struct {
	*internal.SignInRecordsDao
}

var (
	// SignInRecords is a globally accessible object for table sign_in_records operations.
	SignInRecords = signInRecordsDao{internal.NewSignInRecordsDao()}
)

// Add your custom methods and functionality below.
