// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// signConfigDao is the data access object for the table sign_config.
// You can define custom methods on it to extend its functionality as needed.
type signConfigDao struct {
	*internal.SignConfigDao
}

var (
	// SignConfig is a globally accessible object for table sign_config operations.
	SignConfig = signConfigDao{internal.NewSignConfigDao()}
)

// Add your custom methods and functionality below.
