// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// signInRewardsByDayDao is the data access object for the table sign_in_rewards_by_day.
// You can define custom methods on it to extend its functionality as needed.
type signInRewardsByDayDao struct {
	*internal.SignInRewardsByDayDao
}

var (
	// SignInRewardsByDay is a globally accessible object for table sign_in_rewards_by_day operations.
	SignInRewardsByDay = signInRewardsByDayDao{internal.NewSignInRewardsByDayDao()}
)

// Add your custom methods and functionality below.
