// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// siteApkSourceDao is the data access object for the table site_apk_source.
// You can define custom methods on it to extend its functionality as needed.
type siteApkSourceDao struct {
	*internal.SiteApkSourceDao
}

var (
	// SiteApkSource is a globally accessible object for table site_apk_source operations.
	SiteApkSource = siteApkSourceDao{internal.NewSiteApkSourceDao()}
)

// Add your custom methods and functionality below.
