// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// siteDomainDao is the data access object for the table site_domain.
// You can define custom methods on it to extend its functionality as needed.
type siteDomainDao struct {
	*internal.SiteDomainDao
}

var (
	// SiteDomain is a globally accessible object for table site_domain operations.
	SiteDomain = siteDomainDao{internal.NewSiteDomainDao()}
)

// Add your custom methods and functionality below.
