// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// userSignInStatusDao is the data access object for the table user_sign_in_status.
// You can define custom methods on it to extend its functionality as needed.
type userSignInStatusDao struct {
	*internal.UserSignInStatusDao
}

var (
	// UserSignInStatus is a globally accessible object for table user_sign_in_status operations.
	UserSignInStatus = userSignInStatusDao{internal.NewUserSignInStatusDao()}
)

// Add your custom methods and functionality below.
