// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// userMgAccountDao is the data access object for the table user_mg_account.
// You can define custom methods on it to extend its functionality as needed.
type userMgAccountDao struct {
	*internal.UserMgAccountDao
}

var (
	// UserMgAccount is a globally accessible object for table user_mg_account operations.
	UserMgAccount = userMgAccountDao{internal.NewUserMgAccountDao()}
)

// Add your custom methods and functionality below.
