// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// waterConfigDao is the data access object for the table water_config.
// You can define custom methods on it to extend its functionality as needed.
type waterConfigDao struct {
	*internal.WaterConfigDao
}

var (
	// WaterConfig is a globally accessible object for table water_config operations.
	WaterConfig = waterConfigDao{internal.NewWaterConfigDao()}
)

// Add your custom methods and functionality below.
