// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/by_site/dao/internal"
)

// withdrawAccountDao is the data access object for the table withdraw_account.
// You can define custom methods on it to extend its functionality as needed.
type withdrawAccountDao struct {
	*internal.WithdrawAccountDao
}

var (
	// WithdrawAccount is a globally accessible object for table withdraw_account operations.
	WithdrawAccount = withdrawAccountDao{internal.NewWithdrawAccountDao()}
)

// Add your custom methods and functionality below.
