// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/boya/dao/internal"
)

// bankDao is the data access object for the table bank.
// You can define custom methods on it to extend its functionality as needed.
type bankDao struct {
	*internal.BankDao
}

var (
	// Bank is a globally accessible object for table bank operations.
	Bank = bankDao{internal.NewBankDao()}
)

// Add your custom methods and functionality below.
