// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/boya/dao/internal"
)

// paymentBankDao is the data access object for the table payment_bank.
// You can define custom methods on it to extend its functionality as needed.
type paymentBankDao struct {
	*internal.PaymentBankDao
}

var (
	// PaymentBank is a globally accessible object for table payment_bank operations.
	PaymentBank = paymentBankDao{internal.NewPaymentBankDao()}
)

// Add your custom methods and functionality below.
