// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/boya/dao/internal"
)

// withdrawDao is the data access object for the table withdraw.
// You can define custom methods on it to extend its functionality as needed.
type withdrawDao struct {
	*internal.WithdrawDao
}

var (
	// Withdraw is a globally accessible object for table withdraw operations.
	Withdraw = withdrawDao{internal.NewWithdrawDao()}
)

// Add your custom methods and functionality below.
