// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/casion_by/dao/internal"
)

// gfgGameDao is the data access object for the table gfg_game.
// You can define custom methods on it to extend its functionality as needed.
type gfgGameDao struct {
	*internal.GfgGameDao
}

var (
	// GfgGame is a globally accessible object for table gfg_game operations.
	GfgGame = gfgGameDao{internal.NewGfgGameDao()}
)

// Add your custom methods and functionality below.
