// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_balance/dao/internal"
)

// balanceLogBonusPaymentDao is the data access object for the table balance_log_bonus_payment.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusPaymentDao struct {
	*internal.BalanceLogBonusPaymentDao
}

var (
	// BalanceLogBonusPayment is a globally accessible object for table balance_log_bonus_payment operations.
	BalanceLogBonusPayment = balanceLogBonusPaymentDao{internal.NewBalanceLogBonusPaymentDao()}
)

// Add your custom methods and functionality below.
