// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_balance/dao/internal"
)

// balanceChangeDao is the data access object for the table balance_change.
// You can define custom methods on it to extend its functionality as needed.
type balanceChangeDao struct {
	*internal.BalanceChangeDao
}

var (
	// BalanceChange is a globally accessible object for table balance_change operations.
	BalanceChange = balanceChangeDao{internal.NewBalanceChangeDao()}
)

// Add your custom methods and functionality below.
