// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_balance/dao/internal"
)

// balanceLogPaymentDao is the data access object for the table balance_log_payment.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogPaymentDao struct {
	*internal.BalanceLogPaymentDao
}

var (
	// BalanceLogPayment is a globally accessible object for table balance_log_payment operations.
	BalanceLogPayment = balanceLogPaymentDao{internal.NewBalanceLogPaymentDao()}
)

// Add your custom methods and functionality below.
