// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_balance/dao/internal"
)

// balanceLogGameDao is the data access object for the table balance_log_game.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogGameDao struct {
	*internal.BalanceLogGameDao
}

var (
	// BalanceLogGame is a globally accessible object for table balance_log_game operations.
	BalanceLogGame = balanceLogGameDao{internal.NewBalanceLogGameDao()}
)

// Add your custom methods and functionality below.
