// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_balance/dao/internal"
)

// balanceLogBonusRechargeDao is the data access object for the table balance_log_bonus_recharge.
// You can define custom methods on it to extend its functionality as needed.
type balanceLogBonusRechargeDao struct {
	*internal.BalanceLogBonusRechargeDao
}

var (
	// BalanceLogBonusRecharge is a globally accessible object for table balance_log_bonus_recharge operations.
	BalanceLogBonusRecharge = balanceLogBonusRechargeDao{internal.NewBalanceLogBonusRechargeDao()}
)

// Add your custom methods and functionality below.
