// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jh_balance/dao/internal"
)

// balanceUserDao is the data access object for the table balance_user.
// You can define custom methods on it to extend its functionality as needed.
type balanceUserDao struct {
	*internal.BalanceUserDao
}

var (
	// BalanceUser is a globally accessible object for table balance_user operations.
	BalanceUser = balanceUserDao{internal.NewBalanceUserDao()}
)

// Add your custom methods and functionality below.
