// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jinhuang/dao/internal"
)

// gameDao is the data access object for the table game.
// You can define custom methods on it to extend its functionality as needed.
type gameDao struct {
	*internal.GameDao
}

var (
	// Game is a globally accessible object for table game operations.
	Game = gameDao{internal.NewGameDao()}
)

// Add your custom methods and functionality below.
