// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jinhuang/dao/internal"
)

// migrationsDao is the data access object for the table migrations.
// You can define custom methods on it to extend its functionality as needed.
type migrationsDao struct {
	*internal.MigrationsDao
}

var (
	// Migrations is a globally accessible object for table migrations operations.
	Migrations = migrationsDao{internal.NewMigrationsDao()}
)

// Add your custom methods and functionality below.
