// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-service/internal/dao/jinhuang/dao/internal"
)

// paymentGatewayDao is the data access object for the table payment_gateway.
// You can define custom methods on it to extend its functionality as needed.
type paymentGatewayDao struct {
	*internal.PaymentGatewayDao
}

var (
	// PaymentGateway is a globally accessible object for table payment_gateway operations.
	PaymentGateway = paymentGatewayDao{internal.NewPaymentGatewayDao()}
)

// Add your custom methods and functionality below.
