// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"encoding/json"
	"go-service/internal/dao/jinhuang/dao/internal"
	"go-service/internal/dao/jinhuang/model/do"
	"go-service/utility/global"
)

// siteDao is the data access object for the table site.
// You can define custom methods on it to extend its functionality as needed.
type siteDao struct {
	*internal.SiteDao
}

var (
	// Site is a globally accessible object for table site operations.
	Site = siteDao{internal.NewSiteDao()}
)

// Add your custom methods and functionality below.

const StatusOn int = 1 //开启

//GetSiteObject
/**
 * @desc：获取站点对象
 * @return res
 * @return err
 * @author : Carson
 */
func GetSiteObject() (site *do.Site, err error) {
	ctx := context.TODO()
	query := Site.Ctx(ctx)

	where := map[string]interface{}{}
	where["code"] = global.SiteCode
	where["status"] = StatusOn

	result, err := query.Where(where).One()
	if err != nil {
		return nil, err
	}

	// 通过 JSON 序列化来转换
	jsonData, err := json.Marshal(result)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal(jsonData, &site); err != nil {
		return nil, err
	}

	//fmt.Printf("站点信息: %+v\n", site)

	return
}
